[package]
name = "cef-rs"
version = "0.1.0"
authors = ["Peter Suggate <petersuggate@gmail.com>"]
repository = "https://github.com/peter-suggate/cef-rs"
build = "build.rs"

[dependencies]
cef-sys = { path = "../cef-sys" }
libc = "0.2.58"

[build-dependencies]
winres = "0.1.11"
